USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE NOTIFICATION INTEGRATION AZ_IICS_NOTIF_INT
  ENABLED = TRUE
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
  AZURE_STORAGE_QUEUE_PRIMARY_URI = 'https://<AZURE_STORAGE_ACCOUNT>.queue.core.windows.net/iics-snowpipe-queue'
  AZURE_TENANT_ID = '<AZURE_ENTRA_ID>';


