-- 040_create_pipes_customers.sql
-- ENV: DEV
-- Purpose: Create Snowpipe pipes (no auto-ingest yet)

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;
USE SCHEMA RAW;

-- HEADER pipe
CREATE OR REPLACE PIPE PIPE_RAW_CUS_HEADER
  AUTO_INGEST = TRUE
  INTEGRATION = NI_AZ_MF_DEV_Q
AS
COPY INTO RAW.RAW_CUS_HEADER_V (PAYLOAD, FILE_NAME)
FROM (
  SELECT $1, METADATA$FILENAME
  FROM @EXT.STG_AZ_MF_DEV_CUSTOMERS_PROCESSED
)
FILE_FORMAT = (FORMAT_NAME = EXT.FF_JSON_STD)
PATTERN = '.*customer_header.*\.json';

-- DETAIL pipe
CREATE OR REPLACE PIPE PIPE_RAW_CUS_DETAIL
  AUTO_INGEST = TRUE
  INTEGRATION = NI_AZ_MF_DEV_Q
AS
COPY INTO RAW.RAW_CUS_DETAIL_V (PAYLOAD, FILE_NAME)
FROM (
  SELECT $1, METADATA$FILENAME
  FROM @EXT.STG_AZ_MF_DEV_CUSTOMERS_PROCESSED
)
FILE_FORMAT = (FORMAT_NAME = EXT.FF_JSON_STD)
PATTERN = '.*customer_detail.*\.json';

-- TRAILER pipe
CREATE OR REPLACE PIPE PIPE_RAW_CUS_TRAILER
  AUTO_INGEST = TRUE
  INTEGRATION = NI_AZ_MF_DEV_Q
AS
COPY INTO RAW.RAW_CUS_TRAILER_V (PAYLOAD, FILE_NAME)
FROM (
  SELECT $1, METADATA$FILENAME
  FROM @EXT.STG_AZ_MF_DEV_CUSTOMERS_PROCESSED
)
FILE_FORMAT = (FORMAT_NAME = EXT.FF_JSON_STD)
PATTERN = '.*customer_trailer.*\.json';