-- copy/list/system$pipe_status)
-- 041_pipe_validation.sql
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;

SHOW PIPES IN SCHEMA RAW;

-- Optional: force Snowpipe to scan stage and queue loads (use after new files arrive)
-- ALTER PIPE RAW.PIPE_RAW_CUS_DETAIL REFRESH;
-- ALTER PIPE RAW.PIPE_RAW_CUS_HEADER REFRESH;
-- ALTER PIPE RAW.PIPE_RAW_CUS_TRAILER REFRESH;

-- Check status
SELECT SYSTEM$PIPE_STATUS('MF_MODERNIZATION_DEV_DB.RAW.PIPE_RAW_CUS_HEADER');
SELECT SYSTEM$PIPE_STATUS('MF_MODERNIZATION_DEV_DB.RAW.PIPE_RAW_CUS_DETAIL');
SELECT SYSTEM$PIPE_STATUS('MF_MODERNIZATION_DEV_DB.RAW.PIPE_RAW_CUS_TRAILER');

-- After uploading a NEW file to Azure, check ingestion history:
SELECT *
FROM TABLE(INFORMATION_SCHEMA.PIPE_USAGE_HISTORY(
  DATEADD('hour', -2, CURRENT_TIMESTAMP()),
  CURRENT_TIMESTAMP()
))
ORDER BY START_TIME DESC;