-- 030_create_raw_tables.sql
-- ENV: DEV
-- Purpose: RAW landing tables for customer header/detail/trailer JSON

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW_CUS_HEADER_V (
  PAYLOAD     VARIANT,
  FILE_NAME   STRING,
  LOAD_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_CUS_DETAIL_V (
  PAYLOAD     VARIANT,
  FILE_NAME   STRING,
  LOAD_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RAW_CUS_TRAILER_V (
  PAYLOAD     VARIANT,
  FILE_NAME   STRING,
  LOAD_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);