-- 050_create_curated_tables.sql
-- ENV: DEV
-- Purpose: Create curated business tables (safe: no replace)

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;
USE SCHEMA CURATED;

CREATE TABLE IF NOT EXISTS CUS_HEADER (
  FILE_DATE   DATE,
  BATCH_ID    STRING,
  HDR_DESC    STRING,
  LOAD_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CUS_DETAIL (
  FILE_DATE   DATE,
  BATCH_ID    STRING,
  CUST_ID     STRING,
  CUST_NAME   STRING,
  CUST_TYPE   STRING,
  BALANCE     NUMBER(18,2),
  PHONE       STRING,
  STREET      STRING,
  CITY        STRING,
  STATE       STRING,
  TRN_ID      STRING,
  TRN_AMT     NUMBER(18,2),
  SOURCE_FILE STRING,
  LOAD_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CUS_TRAILER (
  FILE_DATE   DATE,
  BATCH_ID    STRING,
  REC_COUNT   NUMBER(18,0),
  TOTAL_AMT   NUMBER(18,2),
  LOAD_TS     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);