-- 051_create_streams_on_raw.sql
-- ENV: DEV
-- Purpose: Streams to capture new RAW rows

SELECT 'HEADER'  AS STREAM, SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_HEADER')
UNION ALL
SELECT 'DETAIL',  SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_DETAIL')
UNION ALL
SELECT 'TRAILER', SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_TRAILER');


USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;
USE SCHEMA RAW;

-- stop tasks
--ALTER TASK CURATED.TSK_CURATE_CUS_HEADER  SUSPEND;
--ALTER TASK CURATED.TSK_CURATE_CUS_DETAIL  SUSPEND;
--ALTER TASK CURATED.TSK_CURATE_CUS_TRAILER SUSPEND;

-- recreate streams as append-only
--DROP STREAM IF EXISTS RAW.STR_RAW_CUS_HEADER;
--DROP STREAM IF EXISTS RAW.STR_RAW_CUS_DETAIL;
--DROP STREAM IF EXISTS RAW.STR_RAW_CUS_TRAILER;

CREATE STREAM RAW.STR_RAW_CUS_HEADER  ON TABLE RAW.RAW_CUS_HEADER_V  APPEND_ONLY = TRUE;
CREATE STREAM RAW.STR_RAW_CUS_DETAIL  ON TABLE RAW.RAW_CUS_DETAIL_V  APPEND_ONLY = TRUE;
CREATE STREAM RAW.STR_RAW_CUS_TRAILER ON TABLE RAW.RAW_CUS_TRAILER_V APPEND_ONLY = TRUE;

SELECT * FROM RAW.RAW_CUS_HEADER_V;