-- 052_create_tasks_curated_merge.sql
-- ENV: DEV
-- Purpose: Idempotent curated loads using MERGE from RAW streams

---- NOT USING ANYMORE AS WE HAVE CREATED ONE SINGLE TASK TO MANAGE MERGER AND AUDIT ETL TABLE
---- NOT USING ANYMORE AS WE HAVE CREATED ONE SINGLE TASK TO MANAGE MERGER AND AUDIT ETL TABLE
---- NOT USING ANYMORE AS WE HAVE CREATED ONE SINGLE TASK TO MANAGE MERGER AND AUDIT ETL TABLE

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;

-- =========================
-- HEADER TASK (MERGE)
-- =========================
CREATE TASK IF NOT EXISTS CURATED.TSK_CURATE_CUS_HEADER
  WAREHOUSE = WH_MF_MODERNIZATION_DEV
  SCHEDULE = NULL
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STR_RAW_CUS_HEADER')
AS
MERGE INTO CURATED.CUS_HEADER T
USING (
  SELECT
    TRY_TO_DATE(PAYLOAD:FILE_DATE::STRING, 'YYYYMMDD') AS FILE_DATE,
    PAYLOAD:BATCH_ID::STRING                           AS BATCH_ID,
    PAYLOAD:HDR_DESC::STRING                           AS HDR_DESC
  FROM RAW.STR_RAW_CUS_HEADER
) S
ON  T.FILE_DATE = S.FILE_DATE
AND T.BATCH_ID  = S.BATCH_ID
WHEN MATCHED THEN UPDATE SET
  HDR_DESC = S.HDR_DESC,
  LOAD_TS  = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (FILE_DATE, BATCH_ID, HDR_DESC)
VALUES (S.FILE_DATE, S.BATCH_ID, S.HDR_DESC);

-- =========================
-- DETAIL TASK (MERGE)
-- =========================
CREATE TASK IF NOT EXISTS CURATED.TSK_CURATE_CUS_DETAIL
  WAREHOUSE = WH_MF_MODERNIZATION_DEV
  SCHEDULE = NULL
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STR_RAW_CUS_DETAIL')
AS
MERGE INTO CURATED.CUS_DETAIL T
USING (
  SELECT
    TRY_TO_DATE(PAYLOAD:FILE_DATE::STRING, 'YYYYMMDD') AS FILE_DATE,
    PAYLOAD:BATCH_ID::STRING                           AS BATCH_ID,
    PAYLOAD:CUST_ID::STRING                            AS CUST_ID,
    PAYLOAD:CUST_NAME::STRING                          AS CUST_NAME,
    PAYLOAD:CUST_TYPE::STRING                          AS CUST_TYPE,
    TRY_TO_DECIMAL(PAYLOAD:BALANCE::STRING, 18, 2)     AS BALANCE,
    PAYLOAD:PHONE::STRING                              AS PHONE,
    PAYLOAD:STREET::STRING                             AS STREET,
    PAYLOAD:CITY::STRING                               AS CITY,
    PAYLOAD:STATE::STRING                              AS STATE,
    PAYLOAD:TRN_ID::STRING                             AS TRN_ID,
    TRY_TO_DECIMAL(PAYLOAD:TRN_AMT::STRING, 18, 2)     AS TRN_AMT,
    FILE_NAME                                          AS SOURCE_FILE
  FROM RAW.STR_RAW_CUS_DETAIL
) S
ON  T.FILE_DATE = S.FILE_DATE
AND T.BATCH_ID  = S.BATCH_ID
AND T.CUST_ID   = S.CUST_ID
AND T.TRN_ID    = S.TRN_ID
WHEN MATCHED THEN UPDATE SET
  CUST_NAME   = S.CUST_NAME,
  CUST_TYPE   = S.CUST_TYPE,
  BALANCE     = S.BALANCE,
  PHONE       = S.PHONE,
  STREET      = S.STREET,
  CITY        = S.CITY,
  STATE       = S.STATE,
  TRN_AMT     = S.TRN_AMT,
  SOURCE_FILE = S.SOURCE_FILE,
  LOAD_TS     = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
  (FILE_DATE, BATCH_ID, CUST_ID, CUST_NAME, CUST_TYPE, BALANCE, PHONE, STREET, CITY, STATE, TRN_ID, TRN_AMT, SOURCE_FILE)
VALUES
  (S.FILE_DATE, S.BATCH_ID, S.CUST_ID, S.CUST_NAME, S.CUST_TYPE, S.BALANCE, S.PHONE, S.STREET, S.CITY, S.STATE, S.TRN_ID, S.TRN_AMT, S.SOURCE_FILE);

-- =========================
-- TRAILER TASK (MERGE)
-- =========================
CREATE TASK IF NOT EXISTS CURATED.TSK_CURATE_CUS_TRAILER
  WAREHOUSE = WH_MF_MODERNIZATION_DEV
  SCHEDULE = NULL
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STR_RAW_CUS_TRAILER')
AS
MERGE INTO CURATED.CUS_TRAILER T
USING (
  SELECT
    TRY_TO_DATE(PAYLOAD:FILE_DATE::STRING, 'YYYYMMDD') AS FILE_DATE,
    PAYLOAD:BATCH_ID::STRING                           AS BATCH_ID,
    TRY_TO_NUMBER(PAYLOAD:REC_COUNT::STRING)           AS REC_COUNT,
    TRY_TO_DECIMAL(PAYLOAD:TOTAL_AMT::STRING, 18, 2)   AS TOTAL_AMT
  FROM RAW.STR_RAW_CUS_TRAILER
) S
ON  T.FILE_DATE = S.FILE_DATE
AND T.BATCH_ID  = S.BATCH_ID
WHEN MATCHED THEN UPDATE SET
  REC_COUNT = S.REC_COUNT,
  TOTAL_AMT = S.TOTAL_AMT,
  LOAD_TS   = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (FILE_DATE, BATCH_ID, REC_COUNT, TOTAL_AMT)
VALUES (S.FILE_DATE, S.BATCH_ID, S.REC_COUNT, S.TOTAL_AMT);