USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;

--TRUNCATE TABLE CURATED.CUS_DETAIL;
--TRUNCATE TABLE CURATED.CUS_HEADER;
--TRUNCATE TABLE CURATED.CUS_TRAILER;
--SELECT * FROM CURATED.CUS_HEADER;
-- sanity
SELECT 'HEADER'  AS T, COUNT(*) AS CNT FROM CURATED.CUS_HEADER
UNION ALL
SELECT 'DETAIL'  AS T, COUNT(*) AS CNT FROM CURATED.CUS_DETAIL
UNION ALL
SELECT 'TRAILER' AS T, COUNT(*) AS CNT FROM CURATED.CUS_TRAILER;


--SELECT * FROM CURATED.CUS_TRAILER ;