GRANT ROLE SYSADMIN TO USER IICS_USER;
GRANT USAGE ON WAREHOUSE WH_MF_MODERNIZATION_DEV TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE MF_MODERNIZATION_DEV_DB TO ROLE SYSADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE MF_MODERNIZATION_DEV_DB TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA MF_MODERNIZATION_DEV_DB.OPS TO ROLE SYSADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA MF_MODERNIZATION_DEV_DB.OPS TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA MF_MODERNIZATION_DEV_DB.OPS TO ROLE SYSADMIN;