-- 001_create_db_and_schemas.sql
-- ENV: DEV
-- Purpose: Create database + core schemas (safe, no replace)

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS MF_MODERNIZATION_DEV_DB;

CREATE SCHEMA IF NOT EXISTS MF_MODERNIZATION_DEV_DB.EXT;
CREATE SCHEMA IF NOT EXISTS MF_MODERNIZATION_DEV_DB.RAW;
CREATE SCHEMA IF NOT EXISTS MF_MODERNIZATION_DEV_DB.CURATED;
CREATE SCHEMA IF NOT EXISTS MF_MODERNIZATION_DEV_DB.OPS;

-- Session context (safe)
USE DATABASE MF_MODERNIZATION_DEV_DB;
USE SCHEMA OPS;