-- 021_create_file_formats.sql
-- ENV: DEV
-- Purpose: Reusable JSON file format

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;
USE SCHEMA EXT;

CREATE OR REPLACE FILE FORMAT FF_JSON_STD
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE;