USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;
USE SCHEMA OPS;

CREATE OR REPLACE NOTIFICATION INTEGRATION NI_AZ_MF_DEV_Q
  ENABLED = TRUE
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
  AZURE_STORAGE_QUEUE_PRIMARY_URI = 'https://<YOUR_AZURE_STORAGE_ACCOUNT>.queue.core.windows.net/snowpipe-mf-dev-q'
  AZURE_TENANT_ID = '<YOUR_AZURE_ENTRA_ID>';

DESC NOTIFICATION INTEGRATION NI_AZ_MF_DEV_Q;