CREATE USER IICS_USER
PASSWORD = '<YOUR_PASSWORD>'
DEFAULT_ROLE = SYSADMIN
DEFAULT_WAREHOUSE = WH_MF_MODERNIZATION_DEV
MUST_CHANGE_PASSWORD = FALSE;

DESC USER IICS_USER;

ALTER USER IICS_USER
SET RSA_PUBLIC_KEY = '<YOUR_KEY>';
