USE ROLE ACCOUNTADMIN;  
USE DATABASE IICS_DB;
USE WAREHOUSE WH_IISC;                     
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS USERS_JSON (
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  FILENAME STRING,
  DATA VARIANT
);
