USE ROLE ACCOUNTADMIN;  
USE DATABASE IICS_DB;
USE WAREHOUSE WH_IISC;                     
USE SCHEMA RAW;

CREATE OR REPLACE PIPE USERS_JSON_PIPE
  AUTO_INGEST = TRUE
  INTEGRATION = 'AZ_IICS_NOTIF_INT'
AS
COPY INTO RAW.USERS_JSON (DATA, LOAD_TS, FILENAME)
FROM (
    SELECT
        $1,
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME
    FROM @AZ_IICS_STAGE
)
FILE_FORMAT = (TYPE = JSON STRIP_OUTER_ARRAY = TRUE);

