USE ROLE ACCOUNTADMIN;  
USE DATABASE IICS_DB;
USE WAREHOUSE WH_IISC;                     
USE SCHEMA RAW;

--SELECT * FROM USERS_JSON;

COPY INTO USERS_JSON (FILENAME, DATA)
FROM (
  SELECT METADATA$FILENAME, $1
  FROM @AZ_IICS_STAGE
)
FILE_FORMAT = (FORMAT_NAME = FF_JSON)
PATTERN = '.*user_status\.json'
ON_ERROR = 'ABORT_STATEMENT';
