USE ROLE ACCOUNTADMIN;  
USE DATABASE IICS_DB;
USE WAREHOUSE WH_IISC;                     
USE SCHEMA CURATED;

CREATE OR REPLACE TASK USERS_UPSERT_TASK
  WAREHOUSE = WH_IISC
  SCHEDULE = '1 MINUTE'
AS
MERGE INTO CURATED.USERS T
USING (
  SELECT
    TRY_TO_NUMBER(TRIM(PARSE_JSON(DATA:"Output"::STRING):id::STRING)) AS ID_N,
    PARSE_JSON(DATA:"Output"::STRING) AS P,
    LOAD_TS,
    FILENAME
  FROM RAW.USERS_JSON_STM
  WHERE ID_N IS NOT NULL
) S
ON T.ID = S.ID_N
WHEN MATCHED THEN UPDATE SET
  NAME = S.P:name::STRING,
  USERNAME = S.P:username::STRING,
  EMAIL = S.P:email::STRING,
  ADDRESS_STREET = S.P:address:street::STRING,
  ADDRESS_SUITE = S.P:address:suite::STRING,
  ADDRESS_CITY = S.P:address:city::STRING,
  ADDRESS_ZIPCODE = S.P:address:zipcode::STRING,
  GEO_LAT = S.P:address:geo:lat::STRING,
  GEO_LNG = S.P:address:geo:lng::STRING,
  PHONE = S.P:phone::STRING,
  WEBSITE = S.P:website::STRING,
  COMPANY_NAME = S.P:company:name::STRING,
  COMPANY_CATCHPHRASE = S.P:company:catchPhrase::STRING,
  COMPANY_BS = S.P:company:bs::STRING,
  LOAD_TS = S.LOAD_TS,
  FILENAME = S.FILENAME
WHEN NOT MATCHED THEN INSERT (
  ID, NAME, USERNAME, EMAIL,
  ADDRESS_STREET, ADDRESS_SUITE, ADDRESS_CITY, ADDRESS_ZIPCODE, GEO_LAT, GEO_LNG,
  PHONE, WEBSITE,
  COMPANY_NAME, COMPANY_CATCHPHRASE, COMPANY_BS,
  LOAD_TS, FILENAME
) VALUES (
  S.ID_N, S.P:name::STRING, S.P:username::STRING, S.P:email::STRING,
  S.P:address:street::STRING, S.P:address:suite::STRING, S.P:address:city::STRING, S.P:address:zipcode::STRING,
  S.P:address:geo:lat::STRING, S.P:address:geo:lng::STRING,
  S.P:phone::STRING, S.P:website::STRING,
  S.P:company:name::STRING, S.P:company:catchPhrase::STRING, S.P:company:bs::STRING,
  S.LOAD_TS, S.FILENAME
);
