USE DATABASE MF_MODERNIZATION_DEV_DB;

--1 suspend task
ALTER TASK OPS.TSK_CURATE_CUSTOMERS_ALL SUSPEND;

--2 clear tables
TRUNCATE TABLE RAW.RAW_CUS_HEADER_V;
TRUNCATE TABLE RAW.RAW_CUS_DETAIL_V;
TRUNCATE TABLE RAW.RAW_CUS_TRAILER_V;

TRUNCATE TABLE CURATED.CUS_HEADER;
TRUNCATE TABLE CURATED.CUS_DETAIL;
TRUNCATE TABLE CURATED.CUS_TRAILER;

TRUNCATE TABLE OPS.ETL_AUDIT_STEP;
TRUNCATE TABLE OPS.ETL_AUDIT_RUN;
TRUNCATE TABLE OPS.IICS_CUSTOMERS_STATUS;

--3 reset streams
CREATE OR REPLACE STREAM RAW.STR_RAW_CUS_HEADER ON TABLE RAW.RAW_CUS_HEADER_V APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM RAW.STR_RAW_CUS_DETAIL ON TABLE RAW.RAW_CUS_DETAIL_V APPEND_ONLY = TRUE;
CREATE OR REPLACE STREAM RAW.STR_RAW_CUS_TRAILER ON TABLE RAW.RAW_CUS_TRAILER_V APPEND_ONLY = TRUE;

--4 resume task
ALTER TASK OPS.TSK_CURATE_CUSTOMERS_ALL RESUME;

--5  now run IICS --- WAIT FOR IIICS MAPPING TO RUN AND AZURE UPLOAD
 -- and run 902_validation_checks.sql steps as mentioned

