-- 031_manual_copy_test.sql
-- ENV: DEV
-- Purpose: Manual load test from external stage into RAW tables

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;

-- HEADER
--TRUNCATE TABLE RAW.RAW_CUS_HEADER_V;
COPY INTO RAW.RAW_CUS_HEADER_V (PAYLOAD, FILE_NAME)
FROM (
  SELECT $1, METADATA$FILENAME
  FROM @EXT.STG_AZ_MF_DEV_CUSTOMERS_PROCESSED
)
FILE_FORMAT = (FORMAT_NAME = EXT.FF_JSON_STD)
PATTERN = '.*customer_header.*\.json';

-- DETAIL
--TRUNCATE TABLE RAW.RAW_CUS_DETAIL_V;
COPY INTO RAW.RAW_CUS_DETAIL_V (PAYLOAD, FILE_NAME)
FROM (
  SELECT $1, METADATA$FILENAME
  FROM @EXT.STG_AZ_MF_DEV_CUSTOMERS_PROCESSED
)
FILE_FORMAT = (FORMAT_NAME = EXT.FF_JSON_STD)
PATTERN = '.*customer_detail.*\.json';

-- TRAILER
--TRUNCATE TABLE RAW.RAW_CUS_TRAILER_V;
COPY INTO RAW.RAW_CUS_TRAILER_V (PAYLOAD, FILE_NAME)
FROM (
  SELECT $1, METADATA$FILENAME
  FROM @EXT.STG_AZ_MF_DEV_CUSTOMERS_PROCESSED
)
FILE_FORMAT = (FORMAT_NAME = EXT.FF_JSON_STD)
PATTERN = '.*customer_trailer.*\.json';

-- sanity
SELECT 'HEADER'  AS T, COUNT(*) AS CNT FROM RAW.RAW_CUS_HEADER_V
UNION ALL
SELECT 'DETAIL'  AS T, COUNT(*) AS CNT FROM RAW.RAW_CUS_DETAIL_V
UNION ALL
SELECT 'TRAILER' AS T, COUNT(*) AS CNT FROM RAW.RAW_CUS_TRAILER_V;

