USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;

ALTER TASK CURATED.TSK_CURATE_CUS_HEADER RESUME;  --now suspended as we are using other task in ops
ALTER TASK CURATED.TSK_CURATE_CUS_DETAIL RESUME;
ALTER TASK CURATED.TSK_CURATE_CUS_TRAILER RESUME;