USE DATABASE MF_MODERNIZATION_DEV_DB;

-- RUN selects one by one in the sequence

-- RAW counts
SELECT 'RAW_HEADER'  AS T, COUNT(*) FROM RAW.RAW_CUS_HEADER_V
UNION ALL
SELECT 'RAW_DETAIL', COUNT(*) FROM RAW.RAW_CUS_DETAIL_V
UNION ALL
SELECT 'RAW_TRAILER',COUNT(*) FROM RAW.RAW_CUS_TRAILER_V;

SELECT * FROM RAW.RAW_CUS_HEADER_V;

 -- CHECK PIPES
-- Check status
SELECT SYSTEM$PIPE_STATUS('MF_MODERNIZATION_DEV_DB.RAW.PIPE_RAW_CUS_HEADER');
SELECT SYSTEM$PIPE_STATUS('MF_MODERNIZATION_DEV_DB.RAW.PIPE_RAW_CUS_DETAIL');
SELECT SYSTEM$PIPE_STATUS('MF_MODERNIZATION_DEV_DB.RAW.PIPE_RAW_CUS_TRAILER');

-- After uploading a NEW file to Azure, check Pipe Ingestion History
SELECT *
FROM TABLE(INFORMATION_SCHEMA.PIPE_USAGE_HISTORY(
  DATEADD('hour', -1, CURRENT_TIMESTAMP()),
  CURRENT_TIMESTAMP()
))
ORDER BY START_TIME DESC;

 --stream status, should be TRUE once snowpipe loads into RAW tables from AZURE. Chages to FALSE when
 --the task loads into curated tables
SELECT 'HEADER'  AS STREAM, SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_HEADER')
UNION ALL
SELECT 'DETAIL',  SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_DETAIL')
UNION ALL
SELECT 'TRAILER', SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_TRAILER');


--8 CURATED counts -- wait 10-15 minutes (15 max), once stream status becomes FALSE
SELECT 'HEADER'  AS T, COUNT(*) AS CNT FROM CURATED.CUS_HEADER
UNION ALL
SELECT 'DETAIL'  AS T, COUNT(*) AS CNT FROM CURATED.CUS_DETAIL
UNION ALL
SELECT 'TRAILER' AS T, COUNT(*) AS CNT FROM CURATED.CUS_TRAILER;

--9 latest audit
SELECT * FROM OPS.ETL_AUDIT_RUN
ORDER BY END_TS DESC
LIMIT 20;


SELECT * FROM OPS.ETL_AUDIT_STEP
ORDER BY LOAD_TS DESC
LIMIT 20;

-- select task history
SELECT NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, ERROR_MESSAGE
FROM TABLE(
  INFORMATION_SCHEMA.TASK_HISTORY(
    SCHEDULED_TIME_RANGE_START => DATEADD('hour', -1, CURRENT_TIMESTAMP())
  )
)
WHERE NAME LIKE 'TSK_CURATE_CUS%'
ORDER BY SCHEDULED_TIME DESC;

SHOW TASKS LIKE 'TSK_CURATE_CUS%';
-- this is used in IICS for getting status and error message (if any)
SELECT
  STATUS,
  COALESCE(ERROR_MESSAGE,'') AS ERROR_MESSAGE
FROM OPS.ETL_AUDIT_RUN
WHERE PIPELINE_NAME = 'CUSTOMERS'
ORDER BY START_TS DESC
LIMIT 1;


SHOW DATABASES LIKE 'MF_MODERNIZATION_DEV_DB';
SHOW SCHEMAS IN DATABASE MF_MODERNIZATION_DEV_DB;
SHOW TABLES IN SCHEMA MF_MODERNIZATION_DEV_DB.OPS;


ALTER PIPE MF_MODERNIZATION_DEV_DB.RAW.PIPE_RAW_CUS_TRAILER REFRESH;

-- check pipe history
SELECT file_name, last_load_time, status, first_error_message
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
  TABLE_NAME => 'MF_MODERNIZATION_DEV_DB.RAW.RAW_CUS_HEADER_V',
  START_TIME => DATEADD('day', -3, CURRENT_TIMESTAMP())
))
ORDER BY last_load_time DESC;


