-- 063_create_task_tsk_curate_customers_all.sql
-- ENV: DEV
-- Purpose: One task to call procedure when any stream has data

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;

CREATE TASK IF NOT EXISTS OPS.TSK_CURATE_CUSTOMERS_ALL
  WAREHOUSE = WH_MF_MODERNIZATION_DEV
  SCHEDULE = '15 MINUTE'
WHEN
  SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_HEADER')
  OR SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_DETAIL')
  OR SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_TRAILER')
AS
CALL OPS.SP_CURATE_CUSTOMERS();

ALTER TASK OPS.TSK_CURATE_CUSTOMERS_ALL RESUME;


