-- 064_suspend_old_tasks.sql

USE ROLE ACCOUNTADMIN;
USE DATABASE MF_MODERNIZATION_DEV_DB;

ALTER TASK IF EXISTS CURATED.TSK_CURATE_CUS_HEADER  SUSPEND;
ALTER TASK IF EXISTS CURATED.TSK_CURATE_CUS_DETAIL  SUSPEND;
ALTER TASK IF EXISTS CURATED.TSK_CURATE_CUS_TRAILER SUSPEND;