-- 061_create_audit_tables_v2.sql
-- ENV: DEV
-- Purpose: Create audit tables for run-level + step-level status (idempotent via MERGE)

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;
USE SCHEMA OPS;

-- 1) One row per pipeline run (IICS checks this)
CREATE TABLE IF NOT EXISTS OPS.ETL_AUDIT_RUN (
  RUN_ID        STRING,
  PIPELINE_NAME STRING,
  FILE_DATE     DATE,
  BATCH_ID      STRING,
  STATUS        STRING,       -- STARTED | SUCCESS | FAILED
  START_TS      TIMESTAMP_NTZ,
  END_TS        TIMESTAMP_NTZ,
  ERROR_MESSAGE STRING,
  CREATED_TS    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 2) One row per step per run (header/detail/trailer)
CREATE TABLE IF NOT EXISTS OPS.ETL_AUDIT_STEP (
  RUN_ID        STRING,
  PIPELINE_NAME STRING,
  STEP_NAME     STRING,       -- CUS_HEADER | CUS_DETAIL | CUS_TRAILER
  FILE_NAME     STRING,
  ROWS_SEEN     NUMBER,
  STATUS        STRING,       -- STARTED | DONE | FAILED | NO_DATA
  LOAD_TS       TIMESTAMP_NTZ,
  ERROR_MESSAGE STRING,
  CREATED_TS    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- (Optional) Cluster keys help query performance; safe to run repeatedly
ALTER TABLE OPS.ETL_AUDIT_RUN  CLUSTER BY (PIPELINE_NAME, BATCH_ID, FILE_DATE, RUN_ID);
ALTER TABLE OPS.ETL_AUDIT_STEP CLUSTER BY (PIPELINE_NAME, RUN_ID, STEP_NAME);