USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;
USE SCHEMA OPS;

CREATE OR REPLACE PROCEDURE OPS.SP_CURATE_CUSTOMERS()
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  v_run_id   STRING DEFAULT UUID_STRING();
  v_pipeline STRING DEFAULT 'CUSTOMERS';
  v_rows     NUMBER DEFAULT 0;
  v_file     STRING DEFAULT NULL;
  v_step     STRING DEFAULT 'START';

  v_file_date DATE DEFAULT NULL;
  v_batch_id  STRING DEFAULT NULL;
BEGIN

  -- =========================
  -- Derive FILE_DATE/BATCH_ID (best-effort)
  -- =========================
  v_step := 'DERIVE_BATCH';

  SELECT
    TRY_TO_DATE(PAYLOAD:FILE_DATE::STRING,'YYYYMMDD'),
    PAYLOAD:BATCH_ID::STRING
  INTO v_file_date, v_batch_id
  FROM MF_MODERNIZATION_DEV_DB.RAW.RAW_CUS_HEADER_V
  QUALIFY ROW_NUMBER() OVER (ORDER BY LOAD_TS DESC) = 1;

  IF (v_batch_id IS NULL) THEN
    SELECT
      TRY_TO_DATE(PAYLOAD:FILE_DATE::STRING,'YYYYMMDD'),
      PAYLOAD:BATCH_ID::STRING
    INTO v_file_date, v_batch_id
    FROM MF_MODERNIZATION_DEV_DB.RAW.RAW_CUS_DETAIL_V
    QUALIFY ROW_NUMBER() OVER (ORDER BY LOAD_TS DESC) = 1;
  END IF;

  IF (v_batch_id IS NULL) THEN
    SELECT
      TRY_TO_DATE(PAYLOAD:FILE_DATE::STRING,'YYYYMMDD'),
      PAYLOAD:BATCH_ID::STRING
    INTO v_file_date, v_batch_id
    FROM MF_MODERNIZATION_DEV_DB.RAW.RAW_CUS_TRAILER_V
    QUALIFY ROW_NUMBER() OVER (ORDER BY LOAD_TS DESC) = 1;
  END IF;

  -- =========================================
  -- RUN row: STARTED (MERGE = idempotent)
  -- =========================================
  v_step := 'RUN_STARTED';

  MERGE INTO OPS.ETL_AUDIT_RUN T
  USING (SELECT :v_run_id AS RUN_ID) S
  ON T.RUN_ID = S.RUN_ID
  WHEN MATCHED THEN UPDATE SET
    PIPELINE_NAME = :v_pipeline,
    FILE_DATE     = :v_file_date,
    BATCH_ID      = :v_batch_id,
    STATUS        = 'STARTED',
    START_TS      = COALESCE(T.START_TS, CURRENT_TIMESTAMP()),
    END_TS        = NULL,
    ERROR_MESSAGE = NULL
  WHEN NOT MATCHED THEN INSERT
    (RUN_ID, PIPELINE_NAME, FILE_DATE, BATCH_ID, STATUS, START_TS, END_TS, ERROR_MESSAGE)
  VALUES
    (:v_run_id, :v_pipeline, :v_file_date, :v_batch_id, 'STARTED', CURRENT_TIMESTAMP(), NULL, NULL);

  -- =========================
  -- HEADER STEP
  -- =========================
  v_step := 'HEADER';

  IF (SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_HEADER')) THEN
    v_step := 'HEADER_COUNT';

    SELECT COUNT(*), MIN(FILE_NAME)
      INTO v_rows, v_file
    FROM MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_HEADER;

    v_step := 'HEADER_STEP_STARTED';

    MERGE INTO OPS.ETL_AUDIT_STEP T
    USING (SELECT :v_run_id RUN_ID, :v_pipeline PIPELINE_NAME, 'CUS_HEADER' STEP_NAME) S
    ON T.RUN_ID=S.RUN_ID AND T.PIPELINE_NAME=S.PIPELINE_NAME AND T.STEP_NAME=S.STEP_NAME
    WHEN MATCHED THEN UPDATE SET
      FILE_NAME = :v_file,
      ROWS_SEEN = :v_rows,
      STATUS    = 'STARTED',
      LOAD_TS   = CURRENT_TIMESTAMP(),
      ERROR_MESSAGE = NULL
    WHEN NOT MATCHED THEN INSERT
      (RUN_ID, PIPELINE_NAME, STEP_NAME, FILE_NAME, ROWS_SEEN, STATUS, LOAD_TS, ERROR_MESSAGE)
    VALUES
      (:v_run_id, :v_pipeline, 'CUS_HEADER', :v_file, :v_rows, 'STARTED', CURRENT_TIMESTAMP(), NULL);

    v_step := 'HEADER_MERGE';

    MERGE INTO MF_MODERNIZATION_DEV_DB.CURATED.CUS_HEADER T
    USING (SELECT PAYLOAD AS P FROM MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_HEADER) X
    ON  T.FILE_DATE = TRY_TO_DATE(X.P:FILE_DATE::STRING,'YYYYMMDD')
    AND T.BATCH_ID  = X.P:BATCH_ID::STRING
    WHEN MATCHED THEN UPDATE SET
      HDR_DESC = X.P:HDR_DESC::STRING,
      LOAD_TS  = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (FILE_DATE, BATCH_ID, HDR_DESC)
    VALUES (
      TRY_TO_DATE(X.P:FILE_DATE::STRING,'YYYYMMDD'),
      X.P:BATCH_ID::STRING,
      X.P:HDR_DESC::STRING
    );

    v_step := 'HEADER_STEP_DONE';

    UPDATE OPS.ETL_AUDIT_STEP
    SET STATUS='DONE', LOAD_TS=CURRENT_TIMESTAMP(), ERROR_MESSAGE=NULL
    WHERE RUN_ID=:v_run_id AND PIPELINE_NAME=:v_pipeline AND STEP_NAME='CUS_HEADER';

  ELSE
    v_step := 'HEADER_NO_DATA';

    MERGE INTO OPS.ETL_AUDIT_STEP T
    USING (SELECT :v_run_id RUN_ID, :v_pipeline PIPELINE_NAME, 'CUS_HEADER' STEP_NAME) S
    ON T.RUN_ID=S.RUN_ID AND T.PIPELINE_NAME=S.PIPELINE_NAME AND T.STEP_NAME=S.STEP_NAME
    WHEN MATCHED THEN UPDATE SET STATUS='NO_DATA', LOAD_TS=CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (RUN_ID, PIPELINE_NAME, STEP_NAME, STATUS, LOAD_TS)
    VALUES (:v_run_id, :v_pipeline, 'CUS_HEADER', 'NO_DATA', CURRENT_TIMESTAMP());
  END IF;

  -- =========================
  -- DETAIL STEP
  -- =========================
  v_step := 'DETAIL';

  IF (SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_DETAIL')) THEN
    v_step := 'DETAIL_COUNT';

    SELECT COUNT(*), MIN(FILE_NAME)
      INTO v_rows, v_file
    FROM MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_DETAIL;

    v_step := 'DETAIL_STEP_STARTED';

    MERGE INTO OPS.ETL_AUDIT_STEP T
    USING (SELECT :v_run_id RUN_ID, :v_pipeline PIPELINE_NAME, 'CUS_DETAIL' STEP_NAME) S
    ON T.RUN_ID=S.RUN_ID AND T.PIPELINE_NAME=S.PIPELINE_NAME AND T.STEP_NAME=S.STEP_NAME
    WHEN MATCHED THEN UPDATE SET FILE_NAME=:v_file, ROWS_SEEN=:v_rows, STATUS='STARTED', LOAD_TS=CURRENT_TIMESTAMP(), ERROR_MESSAGE=NULL
    WHEN NOT MATCHED THEN INSERT (RUN_ID, PIPELINE_NAME, STEP_NAME, FILE_NAME, ROWS_SEEN, STATUS, LOAD_TS, ERROR_MESSAGE)
    VALUES (:v_run_id, :v_pipeline, 'CUS_DETAIL', :v_file, :v_rows, 'STARTED', CURRENT_TIMESTAMP(), NULL);

    v_step := 'DETAIL_MERGE';

    MERGE INTO MF_MODERNIZATION_DEV_DB.CURATED.CUS_DETAIL T
    USING (
      SELECT PAYLOAD AS P, FILE_NAME
      FROM MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_DETAIL
    ) X
    ON  T.FILE_DATE = TRY_TO_DATE(X.P:FILE_DATE::STRING,'YYYYMMDD')
    AND T.BATCH_ID  = X.P:BATCH_ID::STRING
    AND T.CUST_ID   = X.P:CUST_ID::STRING
    AND T.TRN_ID    = X.P:TRN_ID::STRING
    WHEN MATCHED THEN UPDATE SET
      CUST_NAME   = X.P:CUST_NAME::STRING,
      CUST_TYPE   = X.P:CUST_TYPE::STRING,
      BALANCE     = TRY_TO_DECIMAL(X.P:BALANCE::STRING,18,2),
      PHONE       = X.P:PHONE::STRING,
      STREET      = X.P:STREET::STRING,
      CITY        = X.P:CITY::STRING,
      STATE       = X.P:STATE::STRING,
      TRN_AMT     = TRY_TO_DECIMAL(X.P:TRN_AMT::STRING,18,2),
      SOURCE_FILE = X.FILE_NAME,
      LOAD_TS     = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT
      (FILE_DATE,BATCH_ID,CUST_ID,CUST_NAME,CUST_TYPE,BALANCE,PHONE,STREET,CITY,STATE,TRN_ID,TRN_AMT,SOURCE_FILE)
    VALUES
      (TRY_TO_DATE(X.P:FILE_DATE::STRING,'YYYYMMDD'),
       X.P:BATCH_ID::STRING,
       X.P:CUST_ID::STRING,
       X.P:CUST_NAME::STRING,
       X.P:CUST_TYPE::STRING,
       TRY_TO_DECIMAL(X.P:BALANCE::STRING,18,2),
       X.P:PHONE::STRING,
       X.P:STREET::STRING,
       X.P:CITY::STRING,
       X.P:STATE::STRING,
       X.P:TRN_ID::STRING,
       TRY_TO_DECIMAL(X.P:TRN_AMT::STRING,18,2),
       X.FILE_NAME);

    v_step := 'DETAIL_STEP_DONE';

    UPDATE OPS.ETL_AUDIT_STEP
    SET STATUS='DONE', LOAD_TS=CURRENT_TIMESTAMP(), ERROR_MESSAGE=NULL
    WHERE RUN_ID=:v_run_id AND PIPELINE_NAME=:v_pipeline AND STEP_NAME='CUS_DETAIL';

  ELSE
    v_step := 'DETAIL_NO_DATA';

    MERGE INTO OPS.ETL_AUDIT_STEP T
    USING (SELECT :v_run_id RUN_ID, :v_pipeline PIPELINE_NAME, 'CUS_DETAIL' STEP_NAME) S
    ON T.RUN_ID=S.RUN_ID AND T.PIPELINE_NAME=S.PIPELINE_NAME AND T.STEP_NAME=S.STEP_NAME
    WHEN MATCHED THEN UPDATE SET STATUS='NO_DATA', LOAD_TS=CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (RUN_ID, PIPELINE_NAME, STEP_NAME, STATUS, LOAD_TS)
    VALUES (:v_run_id, :v_pipeline, 'CUS_DETAIL', 'NO_DATA', CURRENT_TIMESTAMP());
  END IF;

  -- =========================
  -- TRAILER STEP
  -- =========================
  v_step := 'TRAILER';

  IF (SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_TRAILER')) THEN
    v_step := 'TRAILER_COUNT';

    SELECT COUNT(*), MIN(FILE_NAME)
      INTO v_rows, v_file
    FROM MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_TRAILER;

    v_step := 'TRAILER_STEP_STARTED';

    MERGE INTO OPS.ETL_AUDIT_STEP T
    USING (SELECT :v_run_id RUN_ID, :v_pipeline PIPELINE_NAME, 'CUS_TRAILER' STEP_NAME) S
    ON T.RUN_ID=S.RUN_ID AND T.PIPELINE_NAME=S.PIPELINE_NAME AND T.STEP_NAME=S.STEP_NAME
    WHEN MATCHED THEN UPDATE SET FILE_NAME=:v_file, ROWS_SEEN=:v_rows, STATUS='STARTED', LOAD_TS=CURRENT_TIMESTAMP(), ERROR_MESSAGE=NULL
    WHEN NOT MATCHED THEN INSERT (RUN_ID, PIPELINE_NAME, STEP_NAME, FILE_NAME, ROWS_SEEN, STATUS, LOAD_TS, ERROR_MESSAGE)
    VALUES (:v_run_id, :v_pipeline, 'CUS_TRAILER', :v_file, :v_rows, 'STARTED', CURRENT_TIMESTAMP(), NULL);

    v_step := 'TRAILER_MERGE';

    MERGE INTO MF_MODERNIZATION_DEV_DB.CURATED.CUS_TRAILER T
    USING (SELECT PAYLOAD AS P FROM MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_TRAILER) X
    ON  T.FILE_DATE = TRY_TO_DATE(X.P:FILE_DATE::STRING,'YYYYMMDD')
    AND T.BATCH_ID  = X.P:BATCH_ID::STRING
    WHEN MATCHED THEN UPDATE SET
      REC_COUNT = TRY_TO_NUMBER(X.P:REC_COUNT::STRING),
      TOTAL_AMT = TRY_TO_DECIMAL(X.P:TOTAL_AMT::STRING,18,2),
      LOAD_TS   = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (FILE_DATE,BATCH_ID,REC_COUNT,TOTAL_AMT)
    VALUES (
      TRY_TO_DATE(X.P:FILE_DATE::STRING,'YYYYMMDD'),
      X.P:BATCH_ID::STRING,
      TRY_TO_NUMBER(X.P:REC_COUNT::STRING),
      TRY_TO_DECIMAL(X.P:TOTAL_AMT::STRING,18,2)
    );

    v_step := 'TRAILER_STEP_DONE';

    UPDATE OPS.ETL_AUDIT_STEP
    SET STATUS='DONE', LOAD_TS=CURRENT_TIMESTAMP(), ERROR_MESSAGE=NULL
    WHERE RUN_ID=:v_run_id AND PIPELINE_NAME=:v_pipeline AND STEP_NAME='CUS_TRAILER';

  ELSE
    v_step := 'TRAILER_NO_DATA';

    MERGE INTO OPS.ETL_AUDIT_STEP T
    USING (SELECT :v_run_id RUN_ID, :v_pipeline PIPELINE_NAME, 'CUS_TRAILER' STEP_NAME) S
    ON T.RUN_ID=S.RUN_ID AND T.PIPELINE_NAME=S.PIPELINE_NAME AND T.STEP_NAME=S.STEP_NAME
    WHEN MATCHED THEN UPDATE SET STATUS='NO_DATA', LOAD_TS=CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (RUN_ID, PIPELINE_NAME, STEP_NAME, STATUS, LOAD_TS)
    VALUES (:v_run_id, :v_pipeline, 'CUS_TRAILER', 'NO_DATA', CURRENT_TIMESTAMP());
  END IF;

  -- =========================
  -- RUN SUCCESS
  -- =========================
  v_step := 'RUN_SUCCESS';

  UPDATE OPS.ETL_AUDIT_RUN
  SET STATUS='SUCCESS', END_TS=CURRENT_TIMESTAMP(), ERROR_MESSAGE=NULL
  WHERE RUN_ID=:v_run_id;

  RETURN OBJECT_CONSTRUCT('status','ok','run_id', v_run_id);

EXCEPTION
  WHEN OTHER THEN
    UPDATE OPS.ETL_AUDIT_RUN
    SET STATUS='FAILED', END_TS=CURRENT_TIMESTAMP(), ERROR_MESSAGE='FAILED_AT=' || :v_step
    WHERE RUN_ID=:v_run_id;

    MERGE INTO OPS.ETL_AUDIT_STEP T
    USING (SELECT :v_run_id RUN_ID, :v_pipeline PIPELINE_NAME, 'FAILED' STEP_NAME) S
    ON T.RUN_ID=S.RUN_ID AND T.PIPELINE_NAME=S.PIPELINE_NAME AND T.STEP_NAME=S.STEP_NAME
    WHEN MATCHED THEN UPDATE SET STATUS='FAILED', LOAD_TS=CURRENT_TIMESTAMP(), ERROR_MESSAGE='FAILED_AT=' || :v_step
    WHEN NOT MATCHED THEN INSERT (RUN_ID, PIPELINE_NAME, STEP_NAME, STATUS, LOAD_TS, ERROR_MESSAGE)
    VALUES (:v_run_id, :v_pipeline, 'FAILED', 'FAILED', CURRENT_TIMESTAMP(), 'FAILED_AT=' || :v_step);

    RETURN OBJECT_CONSTRUCT('status','failed','run_id', v_run_id, 'failed_at', v_step);
END;
$$;