-- 060_create_ops_audit.sql
-- ENV: DEV
-- Purpose: Audit/status table for pipeline + IICS status check

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;
USE SCHEMA OPS;

select * from ETL_AUDIT_MF;

CREATE TABLE IF NOT EXISTS ETL_AUDIT_MF (        --   NOT USING ANYMORE. USING AUDIT V2 now
  RUN_ID        STRING,
  FILE_NAME     STRING,
  STAGE_NAME    STRING,
  OBJECT_NAME   STRING,
  ROWS_LOADED   NUMBER(18,0),
  STATUS        STRING,              -- STARTED / RAW_LOADED / CURATED_DONE / FAILED
  ERROR_MESSAGE STRING,
  LOAD_TS       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);