-- 062_create_procedure_sp_curate_customers_FINAL.sql
-- ENV: DEV
-- Purpose: Curate customers (H/D/T) from RAW streams into CURATED + write OPS audit (with FILE_NAME)

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MF_MODERNIZATION_DEV;
USE DATABASE MF_MODERNIZATION_DEV_DB;
USE SCHEMA OPS;

CREATE OR REPLACE PROCEDURE OPS.SP_CURATE_CUSTOMERS()               --- NOT USING ANYMORE.  USING V2 version now
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
  v_run_id STRING DEFAULT UUID_STRING();
  v_rows   NUMBER DEFAULT 0;
  v_file   STRING DEFAULT NULL;
  v_step   STRING DEFAULT 'START';
BEGIN

  -- =========================
  -- HEADER
  -- =========================
  IF (SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_HEADER')) THEN
    v_step := 'HEADER_COUNT';

    SELECT COUNT(*), MIN(FILE_NAME)
      INTO v_rows, v_file
    FROM MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_HEADER;

    v_step := 'HEADER_MERGE';

    MERGE INTO MF_MODERNIZATION_DEV_DB.CURATED.CUS_HEADER T
    USING (
      SELECT PAYLOAD AS P
      FROM MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_HEADER
    ) X
    ON  T.FILE_DATE = TRY_TO_DATE(X.P:FILE_DATE::STRING,'YYYYMMDD')
    AND T.BATCH_ID  = X.P:BATCH_ID::STRING
    WHEN MATCHED THEN UPDATE SET
      HDR_DESC = X.P:HDR_DESC::STRING,
      LOAD_TS  = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (FILE_DATE, BATCH_ID, HDR_DESC)
    VALUES (
      TRY_TO_DATE(X.P:FILE_DATE::STRING,'YYYYMMDD'),
      X.P:BATCH_ID::STRING,
      X.P:HDR_DESC::STRING
    );

    v_step := 'HEADER_AUDIT';

    INSERT INTO OPS.ETL_AUDIT_MF
      (RUN_ID, FILE_NAME, STAGE_NAME, OBJECT_NAME, ROWS_LOADED, STATUS, ERROR_MESSAGE)
    SELECT
      :v_run_id, :v_file, 'AZURE_STAGE', 'CUS_HEADER', :v_rows, 'CURATED_DONE', NULL;

  END IF;


  -- =========================
  -- DETAIL
  -- =========================
  IF (SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_DETAIL')) THEN
    v_step := 'DETAIL_COUNT';

    SELECT COUNT(*), MIN(FILE_NAME)
      INTO v_rows, v_file
    FROM MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_DETAIL;

    v_step := 'DETAIL_MERGE';

    MERGE INTO MF_MODERNIZATION_DEV_DB.CURATED.CUS_DETAIL T
    USING (
      SELECT PAYLOAD AS P, FILE_NAME
      FROM MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_DETAIL
    ) X
    ON  T.FILE_DATE = TRY_TO_DATE(X.P:FILE_DATE::STRING,'YYYYMMDD')
    AND T.BATCH_ID  = X.P:BATCH_ID::STRING
    AND T.CUST_ID   = X.P:CUST_ID::STRING
    AND T.TRN_ID    = X.P:TRN_ID::STRING
    WHEN MATCHED THEN UPDATE SET
      CUST_NAME   = X.P:CUST_NAME::STRING,
      CUST_TYPE   = X.P:CUST_TYPE::STRING,
      BALANCE     = TRY_TO_DECIMAL(X.P:BALANCE::STRING,18,2),
      PHONE       = X.P:PHONE::STRING,
      STREET      = X.P:STREET::STRING,
      CITY        = X.P:CITY::STRING,
      STATE       = X.P:STATE::STRING,
      TRN_AMT     = TRY_TO_DECIMAL(X.P:TRN_AMT::STRING,18,2),
      SOURCE_FILE = X.FILE_NAME,
      LOAD_TS     = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT
      (FILE_DATE,BATCH_ID,CUST_ID,CUST_NAME,CUST_TYPE,BALANCE,PHONE,STREET,CITY,STATE,TRN_ID,TRN_AMT,SOURCE_FILE)
    VALUES
      (TRY_TO_DATE(X.P:FILE_DATE::STRING,'YYYYMMDD'),
       X.P:BATCH_ID::STRING,
       X.P:CUST_ID::STRING,
       X.P:CUST_NAME::STRING,
       X.P:CUST_TYPE::STRING,
       TRY_TO_DECIMAL(X.P:BALANCE::STRING,18,2),
       X.P:PHONE::STRING,
       X.P:STREET::STRING,
       X.P:CITY::STRING,
       X.P:STATE::STRING,
       X.P:TRN_ID::STRING,
       TRY_TO_DECIMAL(X.P:TRN_AMT::STRING,18,2),
       X.FILE_NAME);

    v_step := 'DETAIL_AUDIT';

    INSERT INTO OPS.ETL_AUDIT_MF
      (RUN_ID, FILE_NAME, STAGE_NAME, OBJECT_NAME, ROWS_LOADED, STATUS, ERROR_MESSAGE)
    SELECT
      :v_run_id, :v_file, 'AZURE_STAGE', 'CUS_DETAIL', :v_rows, 'CURATED_DONE', NULL;

  END IF;


  -- =========================
  -- TRAILER
  -- =========================
  IF (SYSTEM$STREAM_HAS_DATA('MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_TRAILER')) THEN
    v_step := 'TRAILER_COUNT';

    SELECT COUNT(*), MIN(FILE_NAME)
      INTO v_rows, v_file
    FROM MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_TRAILER;

    v_step := 'TRAILER_MERGE';

    MERGE INTO MF_MODERNIZATION_DEV_DB.CURATED.CUS_TRAILER T
    USING (
      SELECT PAYLOAD AS P
      FROM MF_MODERNIZATION_DEV_DB.RAW.STR_RAW_CUS_TRAILER
    ) X
    ON  T.FILE_DATE = TRY_TO_DATE(X.P:FILE_DATE::STRING,'YYYYMMDD')
    AND T.BATCH_ID  = X.P:BATCH_ID::STRING
    WHEN MATCHED THEN UPDATE SET
      REC_COUNT = TRY_TO_NUMBER(X.P:REC_COUNT::STRING),
      TOTAL_AMT = TRY_TO_DECIMAL(X.P:TOTAL_AMT::STRING,18,2),
      LOAD_TS   = CURRENT_TIMESTAMP()
    WHEN NOT MATCHED THEN INSERT (FILE_DATE,BATCH_ID,REC_COUNT,TOTAL_AMT)
    VALUES (
      TRY_TO_DATE(X.P:FILE_DATE::STRING,'YYYYMMDD'),
      X.P:BATCH_ID::STRING,
      TRY_TO_NUMBER(X.P:REC_COUNT::STRING),
      TRY_TO_DECIMAL(X.P:TOTAL_AMT::STRING,18,2)
    );

    v_step := 'TRAILER_AUDIT';

    INSERT INTO OPS.ETL_AUDIT_MF
      (RUN_ID, FILE_NAME, STAGE_NAME, OBJECT_NAME, ROWS_LOADED, STATUS, ERROR_MESSAGE)
    SELECT
      :v_run_id, :v_file, 'AZURE_STAGE', 'CUS_TRAILER', :v_rows, 'CURATED_DONE', NULL;

  END IF;


  RETURN OBJECT_CONSTRUCT('status','ok','run_id', v_run_id);

EXCEPTION
  WHEN OTHER THEN
    INSERT INTO OPS.ETL_AUDIT_MF
      (RUN_ID, FILE_NAME, STAGE_NAME, OBJECT_NAME, ROWS_LOADED, STATUS, ERROR_MESSAGE)
    SELECT
      :v_run_id, :v_file, 'AZURE_STAGE', 'CUSTOMERS', NULL, 'FAILED', 'FAILED_AT=' || :v_step;

    RETURN OBJECT_CONSTRUCT('status','failed','run_id', v_run_id, 'failed_at', v_step);
END;
$$;