USE ROLE ACCOUNTADMIN;  
USE DATABASE IICS_DB;
USE WAREHOUSE WH_IISC;                     
USE SCHEMA CURATED;

CREATE OR REPLACE TABLE IICS_DB.CURATED.USERS_DEDUP AS
SELECT *
FROM IICS_DB.CURATED.USERS
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY TRY_TO_NUMBER(TRIM(ID::STRING))
- ORDER BY LOAD_TS DESC, COALESCE(FILENAME,'') DESC
) = 1;


-- swap
DROP TABLE USERS_OLD;
ALTER TABLE CURATED.USERS RENAME TO USERS_OLD;
ALTER TABLE CURATED.USERS_DEDUP RENAME TO USERS;

-- optional: drop old after checking
-- DROP TABLE CURATED.USERS_OLD;
