--SHOW SCHEMAS IN DATABASE IICS_DB;

--SHOW OBJECTS IN SCHEMA IICS_DB.PUBLIC;
--SHOW OBJECTS IN SCHEMA IICS_DB.RAW;
--SHOW OBJECTS IN SCHEMA IICS_DB.CURATED;

--SHOW PIPES IN ACCOUNT;
--SHOW STREAMS IN ACCOUNT;
--SHOW TASKS IN ACCOUNT;
--SHOW STAGES IN ACCOUNT;
--SHOW FILE FORMATS IN ACCOUNT;
--SHOW NOTIFICATION INTEGRATIONS;
--SHOW STORAGE INTEGRATIONS;
