USE ROLE ACCOUNTADMIN;  
USE DATABASE IICS_DB;
USE WAREHOUSE WH_IISC;                     
USE SCHEMA CURATED;

CREATE TABLE IF NOT EXISTS USERS (
  ID               NUMBER,
  NAME             STRING,
  USERNAME         STRING,
  EMAIL            STRING,

  ADDRESS_STREET   STRING,
  ADDRESS_SUITE    STRING,
  ADDRESS_CITY     STRING,
  ADDRESS_ZIPCODE  STRING,
  GEO_LAT          STRING,
  GEO_LNG          STRING,

  PHONE            STRING,
  WEBSITE          STRING,

  COMPANY_NAME        STRING,
  COMPANY_CATCHPHRASE STRING,
  COMPANY_BS          STRING,

  LOAD_TS          TIMESTAMP_NTZ,
  FILENAME         STRING
);
