USE ROLE ACCOUNTADMIN;  
USE DATABASE IICS_DB;
USE WAREHOUSE WH_IISC;                     
USE SCHEMA CURATED;

--RESUME to start, SUSPEND to pause
ALTER TASK CURATED.USERS_UPSERT_TASK RESUME; 
--SHOW TASKS IN SCHEMA CURATED;
