USE ROLE ACCOUNTADMIN;  

CREATE OR REPLACE NOTIFICATION INTEGRATION AZ_IICS_NOTIF_INT
  ENABLED = TRUE
  TYPE = QUEUE
  NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
  AZURE_STORAGE_QUEUE_PRIMARY_URI = 'https://atheriicsstorage.queue.core.windows.net/iics-snowpipe-queue'
  AZURE_TENANT_ID = '5776bb0c-9c4d-40bc-80b6-4d269cc789f3';

  
